main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve
from main import views

urlpatterns = [
    url(r"^$", views.home, name="home"),
    url(r"^about/$", views.about, name="about"),
    url(r"^account/$", views.account, name="account"),
    url(r"^update/$", views.update_countdown, name="countdown-update"),
    url(r"^webhook/notifications/$", views.webhook_notifications, name="webhook-notifications"),
    url(r"^(?P<countdown_id>[^/]{6})/$", views.view_countdown, name="countdown-view"),
    url(r"^(?P<countdown_id>[^/]{6})/embed/$", views.view_embed, name="embed-view"),
    url(r"^(?P<countdown_id>[^/]{6})/delete/$", views.delete_countdown, name="delete-countdown"),
]

if settings.DEBUG:
    urlpatterns += [url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT, "show_indexes": True})]

timetaco/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r"^auth/", include("tokenauth.urls", namespace="tokenauth")),
    url(r"^entrary/", admin.site.urls),
    url(r"^", include("main.urls", namespace="main")),
    url(r"^webpush/", include("webpush.urls")),
]

main/models.py
from __future__ import unicode_literals

from datetime import datetime
from typing import Union

import requests
import shortuuid
from django.conf import settings
from django.contrib.auth import get_user_model, user_logged_in
from django.core.urlresolvers import reverse
from django.db import models
from django.db.utils import IntegrityError
from django.dispatch import receiver
from webpush import send_group_notification


def td_format(td_object):
    # From http://stackoverflow.com/a/13756038/28196.
    seconds = int(td_object.total_seconds())
    periods = [
        ("year", 60 * 60 * 24 * 365),
        ("month", 60 * 60 * 24 * 30),
        ("day", 60 * 60 * 24),
        ("hour", 60 * 60),
        ("minute", 60),
        ("second", 1),
    ]

    strings = []
    for period_name, period_seconds in periods:
        if seconds >= period_seconds:
            period_value, seconds = divmod(seconds, period_seconds)
            if period_value == 1:
                strings.append("%s %s" % (period_value, period_name))
            else:
                strings.append("%s %ss" % (period_value, period_name))

    return strings[0]


def uploaded_filename(instance, filename: str) -> str:
    if "." in filename:
        ext = filename.rsplit(".", 1)[-1].lower().strip()
    else:
        ext = "jpg"
    return "backgrounds/{}.{}".format(instance.pk, ext)


def generate_key() -> str:
    "Create an key."
    return shortuuid.ShortUUID().random(8)


def generate_uuid() -> str:
    "Create a UUID for an object."
    return shortuuid.ShortUUID("abdcefghjkmnpqrstuvwxyz").random()[:6]


class CountdownManager(models.Manager):
    def create(self, *args, **kwargs):
        """Create an object, retrying if there's an ID collision."""

        # Try to create new IDs for the object if one collides.
        tries = 10
        for x in range(tries):
            try:
                obj = super().create(*args, **kwargs)
            except IntegrityError:
                continue
            else:
                break
        else:
            raise IntegrityError("Could not find an ID after %s tries." % tries)

        return obj


class Countdown(models.Model):
    """The main countdown object."""

    # The countdown ID will also be its URL.
    id = models.CharField(max_length=100, primary_key=True, default=generate_uuid, editable=False)
    # The user that created this countdown.
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=True, null=True)
    # The target date of the countdown.
    target = models.DateTimeField(db_index=True)
    # The title to be displayed on the countdown page.
    title = models.CharField(max_length=100, blank=True)
    # When the countdown was created.
    created = models.DateTimeField(auto_now_add=True)
    # The key the user can use to edit the countdown.
    key = models.CharField(max_length=64, default=generate_key)
    # The background image URL.
    background_url = models.CharField(max_length=10000, blank=True)
    # Whether the notification for this countdown has been sent.
    notification_sent = models.BooleanField(default=False, db_index=True)
    # Unsplash photo author name
    unsplash_author_name = models.CharField(max_length=10000, blank=True)
    # Unsplash photo author url
    unsplash_author_url = models.CharField(max_length=10000, blank=True)

    objects = CountdownManager()

    def __str__(self) -> str:
        return self.id

    def delete(self, *args, **kwargs):
        if self.background_url:
            version, url = self.background_url.rsplit("/")[-2:]
            name = url.split(".")[0]

            requests.delete(
                "https://api.cloudinary.com/v1_1/timetaco/resources/image/upload/",
                auth=settings.CLOUDINARY_CREDENTIALS,
                data={"public_ids": name},
            )
        super().delete(*args, **kwargs)

    @property
    def title_or_default(self) -> str:
        return self.title if self.title else "Taco"

    def get_og_image_url(self) -> Union[str, None]:
        """
        Return the URL for the resized background image, for the OpenGraph tag.
        """
        if settings.CLOUDINARY_IMAGES and self.background_url:
            version, url = self.background_url.rsplit("/")[-2:]

            return (
                "https://res.cloudinary.com/timetaco/image/upload/c_fill,h_630,w_1200,f_auto/l_one_pixel,w_1200,h_630,e_colorize,co_rgb:EEE36D,o_50/w_1000,c_fit,l_text:Helvetica_100_bold:%s%%0A%s,co_rgb:6C59A3/%s/%s"
                % (self.title_or_default, self.target, version, url)
            )

        return None

    def get_background_url(self) -> Union[str, None]:
        """
        Return the URL for the background image.
        Doesn't allow the generated image to be larger than 1000x1000.
        """
        if settings.CLOUDINARY_IMAGES and self.background_url:
            version, url = self.background_url.rsplit("/")[-2:]

            return "https://res.cloudinary.com/timetaco/image/upload/w_1000,h_1000,c_limit,f_auto/%s/%s" % (
                version,
                url,
            )

        return None

    def get_absolute_url(self) -> str:
        return reverse("main:countdown-view", args=[self.id])

    def time_to_target(self) -> str:
        """
        Return a string that contains the approximate time to target.

        Example: "has already expired", "expires in 1 day", "expires in 2 hours".
        """
        delta = self.target - datetime.utcnow()
        if delta.total_seconds() < 0:
            return "has ended"
        else:
            return "ends in %s" % td_format(delta)
        return delta

    def send_notification(self):
        """
        Send a notification to subscribed users.
        """
        payload = {
            "head": "TimeTaco notification",
            "body": "%s %s!" % (self.title_or_default, self.time_to_target()),
            "id": self.id,
        }

        try:
            send_group_notification(group_name=self.id, payload=payload, ttl=30 * 60)
        except:  # noqa
            # Ignore whatever goes wrong here.
            pass

        self.notification_sent = True
        self.save()


@receiver(user_logged_in)
def user_login(sender, request, user, **kwargs):
    # Associate a user's anonymous countdowns with their account.
    user_countdowns = Countdown.objects.filter(id__in=request.session.get("tacos", []))
    for countdown in user_countdowns:
        countdown.user = user
        countdown.save()

main/forms.py
from django import forms

from .models import Countdown


class CountdownForm(forms.ModelForm):
    class Meta:
        model = Countdown
        fields = ["target", "title", "background_url", "unsplash_author_name", "unsplash_author_url"]

main/views.py
import datetime

from annoying.decorators import render_to
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.crypto import constant_time_compare
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.http import require_http_methods

from .forms import CountdownForm
from .models import Countdown


@render_to("home.html")
def home(request):
    "Render the home page."

    is_producthunt = request.GET.get("ref") == "producthunt"

    return {"form": CountdownForm(), "producthunt": is_producthunt}


@login_required()
@render_to("account.html")
def account(request):
    "Render the account page."

    countdowns = Countdown.objects.filter(user=request.user)

    return {"countdowns": countdowns}


@render_to("about.html")
def about(request):
    "Render the about page."

    return {}


@login_required()
def delete_countdown(request, countdown_id):
    countdown = get_object_or_404(Countdown, pk=countdown_id, user=request.user)
    countdown.delete()
    messages.success(request, "Your taco has been deleted.")
    return redirect("main:account")


def webhook_notifications(request):
    # Get the current UTC date and look 30 minutes in the future
    ending_date = datetime.datetime.utcnow() + datetime.timedelta(seconds=settings.EXPIRING_COUNTER_INTERVAL)
    countdowns = Countdown.objects.filter(target__lte=ending_date).exclude(notification_sent=True)

    for countdown in countdowns:
        countdown.send_notification()

    return HttpResponse("OK")


@require_http_methods(["POST"])
def update_countdown(request):
    "Create or alter a countdown."
    if request.GET.get("id"):
        countdown = Countdown.objects.filter(pk=request.GET["id"]).first()
        if not countdown:
            messages.error(request, "No such countdown exists.")
            return redirect("main:home")
        if not constant_time_compare(request.GET.get("key", ""), countdown.key):
            messages.error(request, "The update key was invalid.")
            return redirect("main:home")
        form = CountdownForm(request.POST, request.FILES, instance=countdown, initial={"user": request.user})
    else:
        form = CountdownForm(request.POST, request.FILES, initial={"user": request.user})

    new_countdown = form.save(commit=False)
    new_countdown.notification_sent = False
    if request.user.is_authenticated:
        new_countdown.user = request.user
    new_countdown.save()

    if request.GET.get("id"):
        messages.success(request, "Your countdown has been created!")
    else:
        messages.success(request, "Your countdown has been updated!")

    if request.user.is_anonymous:
        # If the user is anonymous, store their created countdowns in their session.
        request.session["tacos"] = request.session.get("tacos", []) + [new_countdown.id]

    return redirect(new_countdown)


@render_to("view_countdown.html")
def view_countdown(request, countdown_id):
    "Show a countdown."
    countdown = get_object_or_404(Countdown, pk=countdown_id)

    show_edit = constant_time_compare(request.GET.get("key", ""), countdown.key)
    is_owner = countdown.user == request.user or countdown_id in request.session.get("tacos", []) or show_edit

    if show_edit:
        return TemplateResponse(request, "home.html", {"countdown": countdown})

    webpush = {"group": countdown.id}

    return {
        "countdown": countdown,
        "is_owner": is_owner,
        "webpush": webpush,
        "vapid_public_key": getattr(settings, "WEBPUSH_SETTINGS", {}).get("VAPID_PUBLIC_KEY", ""),
    }


@xframe_options_exempt
@render_to("embed.html")
def view_embed(request, countdown_id):
    countdown = get_object_or_404(Countdown, pk=countdown_id)

    return {"countdown": countdown, "host": request.GET.get("host", "")}

main/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}About TimeTaco{% endblock %}

{% block background %} class="about-page"{% endblock %}

{% block content %}
	<article>

		<h1><a href="{% url "main:home" %}">TimeTaco</a></h1>

		<p>Here at TimeTaco&trade; (🕐🌮&trade;) Industries, we source only the finest, accuratest, fairtrade countdown timers and offer them to you at cut-throat prices: Free!</p>

        <p>Tired of all the other ad-ridden, slow, nonfunctional countdown timer websites? TimeTaco&trade; provides easy, functional countdown timers that won't bug you with ads or ask you to pay.</p>

        <p>TimeTaco&trade;-brand countdown timers will even send you a push notification when it's time for the event, so you never miss a thing! We'll even throw in timezone handling without you having to think about it, so you can send your countdowns to your friends without worry.</p>

        <p>TimeTaco&trade;-brand countdown timers are the only countdown timers* that allow you to set your own background, or use random, beautiful backgrounds from Unsplash.</p>

        <p>Buy TimeTaco&trade; timers today, and remember: They're free and come with a no-questions-asked money-back guarantee!</p>

        <p>Want to give us feedback, tell us you love the service, or complain about how we've wronged you?<br><a href="https://gitlab.com/stavros/TimeTaco/-/issues" target="_blank">Open an issue</a> today!</p>

        <small>* This statement may be a lie.</small>

		<div class="cta-container">
			<a href="{% url "main:home" %}" class="cta">Create your countdown timer</a>
		</div>

	</article>
{% endblock %}

main/templates/account.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Account Details{% endblock %}

{% block background %} class="account-page"{% endblock %}

{% block content %}
<article class="account-details">

	<header>
		<a class="create-button" href="{% url "main:home" %}">
			<svg width="155px" height="130px" viewBox="0 0 155 130" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Page-1"stroke-width="1" fill-rule="evenodd"><g id="logout-copy" transform="translate(-213.000000, -191.000000)"><g id="Group" transform="translate(213.044137, 190.500000)"><path d="M73.2104537,57.2905434 L20.107454,4.18796323 C15.6019662,-0.317524621 8.29685818,-0.317944165 3.79095078,4.18796323 C-0.714537073,8.69345109 -0.714537073,15.9989786 3.79095078,20.5044665 L48.8957551,65.6084317 L3.79137032,110.712816 C-0.714117529,115.217885 -0.714117529,122.522993 3.79137032,127.02932 C8.29685818,131.534388 15.6023857,131.534388 20.1078735,127.02932 L73.2104537,73.9267395 C75.5041032,71.63309 76.6272237,68.6144677 76.5856888,65.6088512 C76.6268042,62.6028153 75.5036837,59.5837734 73.2104537,57.2905434 Z" id="Path" transform="translate(38.499317, 65.608405) scale(-1, 1) translate(-38.499317, -65.608405) "></path><path d="M24.3967531,65.6084055 L144.396753,65.6084055" id="Line-3" stroke-width="23" stroke-linecap="round" stroke-linejoin="round"></path></g></g></g></svg>
		</a>

		<span class="user">
			<span data-gravatar="{{ request.user.email }}" class="avatar">&nbsp;</span>

			<em>{{ request.user.email }}</em>
		</span>

		<a class="logout-button" href="{% url "tokenauth:logout" %}">Log out</a>
	</header>

</article>

<article class="taco-list">

	{% if countdowns %}
	<h2>Your Tacos</h2>

		<ul>
		{% for countdown in countdowns %}
		<li class="taco">
			<span class="icon" data-icon="{{ countdown.get_background_url }}">&nbsp;</span>
			<div>
				<h5><a href="{% url "main:countdown-view" countdown.id %}">{{ countdown.title_or_default }}</a></h5>
				<p>{{ countdown.target }} UTC</p>
			</div>
			<div class="actions">
				<a title="Edit" href="{% url "main:countdown-view" countdown.id %}?key={{ countdown.key }}" class="edit">
					<svg width="513px" height="513px" viewBox="0 0 513 513" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="edit" stroke="none" stroke-width="1" fill-rule="evenodd"><g id="pencil-alt" transform="translate(95.000000, 95.000000)" fill-rule="nonzero"><path d="M313.637077,89.8757707 L284.643945,118.868903 C281.688029,121.824819 276.90825,121.824819 273.952334,118.868903 L204.142406,49.0589751 C201.186491,46.1030592 201.186491,41.3232804 204.142406,38.3673645 L233.135539,9.37423227 C244.89631,-2.38653936 264.015426,-2.38653936 275.839089,9.37423227 L313.637077,47.1722203 C325.460741,58.9329919 325.460741,78.0521073 313.637077,89.8757707 Z M179.237243,63.2725279 L14.0833055,228.426465 L0.75023819,304.840035 C-1.07362479,315.154295 7.91990646,324.084934 18.2341661,322.323963 L94.6477358,308.928004 L259.801673,143.774066 C262.757589,140.818151 262.757589,136.038372 259.801673,133.082456 L189.991745,63.2725279 C186.972938,60.3166121 182.193159,60.3166121 179.237243,63.2725279 Z"></path></g></g></svg>
				</a>
                <form data-confirm="Are you sure you want to delete this taco?" action="{% url "main:delete-countdown" countdown.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">
						<svg width="513px" height="513px" viewBox="0 0 513 513" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="delete" stroke="none" stroke-width="1" fill-rule="evenodd"><path d="M160.263868,173.557365 L353.549703,173.557365 L353.549703,384.053038 C353.549703,396.088541 352.296557,400.452905 349.943411,404.852905 C347.590265,409.252905 344.13712,412.706051 339.73712,415.059197 C335.33712,417.412343 330.972755,418.665488 318.937252,418.665488 L194.876318,418.665488 C182.840815,418.665488 178.476451,417.412343 174.076451,415.059197 C169.676451,412.706051 166.223305,409.252905 163.870159,404.852905 C161.517014,400.452905 160.263868,396.088541 160.263868,384.053038 L160.263868,173.557365 Z M207.278069,126.505426 L207.278069,118.099484 C207.278069,110.298695 208.090293,107.46994 209.61548,104.618088 C211.140667,101.766237 213.378817,99.5280866 216.230669,98.0028995 C219.082521,96.4777125 221.911275,95.6654884 229.712064,95.6654884 L283.74257,95.6654884 C291.543359,95.6654884 294.372114,96.4777125 297.223966,98.0028995 C300.075818,99.5280866 302.313968,101.766237 303.839155,104.618088 C305.364342,107.46994 306.176566,110.298695 306.176566,118.099484 L306.176566,126.505426 L351.494911,126.505426 C359.2957,126.505426 362.124455,127.31765 364.976307,128.842837 C367.828159,130.368024 370.066309,132.606174 371.591496,135.458026 C373.116683,138.309878 373.928907,141.138632 373.928907,148.939421 L373.928907,157.083723 L139.525728,157.083723 L139.525728,148.939421 C139.525728,141.138632 140.337952,138.309878 141.863139,135.458026 C143.388326,132.606174 145.626476,130.368024 148.478328,128.842837 C151.33018,127.31765 154.158934,126.505426 161.959723,126.505426 L207.278069,126.505426 Z"></path></g></svg>
                    </button>
                </form>
			</div>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p class="no-tacos">You haven't made any tacos yet.<br/>Go on, <a href="{% url "main:home" %}">make one</a>!</p>
	{% endif %}

</article>



{% endblock %}

main/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover"/>
    <title>{{ request.site.name }} - {% block title %}{% endblock %}</title>
    <meta name="description" content="Create a free countdown timer to any date with time zone, embed, custom background image and push notification support to when the event ends.">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="TimeTaco">
    <meta name="twitter:site" content="@timetaco_com">
    <meta name="twitter:description" content="TimeTaco is a free countdown timer to any date with full time zone, embed and custom background image support. TimeTaco also notifies you when a countdown is about to expire with a push notification!">
    <meta name="twitter:image" content="https://{{ request.site.domain }}{% static "images/timetaco-ogimage.png" %}"/>
    <meta name="twitter:image:alt" content="TimeTaco is a free countdown timer to any date with full time zone, embed and custom background image support. TimeTaco also notifies you when a countdown is about to expire with a push notification!">
    {% block headcontent %}{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:700" rel="stylesheet"/>
    <link href="{% static "css/style.css" %}" rel="stylesheet"/>
    <script src="{% static "js/countdown.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
    <script src="{% static "js/colorthief.js" %}"></script>
    <link rel="shortcut icon" type="image/x-icon" href="{% static "icons/favicon.ico" %}">
</head>
<body{% block background %}{% endblock %}>
{% if not settings.DEBUG %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-51110-29', 'auto');
  ga('send', 'pageview');
</script>
{% endif %}

  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

    {% block content %}
    {% endblock %}
</body>
</html>

main/templates/countdown_push_body.html
<div id="webpush-data" {% if webpush.group %} data-group="{{ webpush.group }}" {% endif %} data-url="{% url "save_webpush_info" %}" hidden></div>

main/templates/countdown_push_head.html
{% load staticfiles %}

<script id="service-worker-js" type="text/javascript" src="{% static 'js/serviceworker.js' %}"></script>
<meta name="django-webpush-vapid-key" content="{{ vapid_public_key }}">

main/templates/embed.html
{% load staticfiles %}<!doctype html>
<html id="page-widget">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
        <link href="{% static "css/embed.css" %}" rel="stylesheet"/>
        <script src="{% static "js/countdown.js" %}"></script>
        <script src="{% static "js/script.js" %}"></script>
    </head>
    <body {% if countdown.get_background_url %} style="background-image: url('{{ countdown.get_background_url }}')"{% else %} class="pattern"{% endif %}>

        <article id="timetaco-embed">
            <section class="enabled">
                <div class="countdown-container" id="countdown-parent" title="{{ countdown.title_or_default }} ends at {{ countdown.target }} UTC">
                    {% if countdown.title %}
                    <h1 id="title"><a href="https://{{ request.site.domain }}{% url "main:countdown-view" countdown.id %}" target="_blank">{{ countdown.title }}</a></h1>
                    {% endif %}
                    <div id="countdown" data-year="{{ countdown.target.year }}" data-month="{{ countdown.target.month }}" data-day="{{ countdown.target.day }}" data-hour="{{ countdown.target.hour }}" data-minute="{{ countdown.target.minute }}"></div>
                </div>
            </section>

            {% if countdown.unsplash_author_name %}
            <em class="attribution"><a href="{{ countdown.unsplash_author_url }}?utm_source=TimeTaco&utm_medium=referral&utm_campaign=api-credit" target="_blank" title="{{ countdown.unsplash_author_name }}">{{ countdown.unsplash_author_name }}</a> <span>/</span> <a href="https://unsplash.com?utm_source=TimeTaco&utm_medium=referral&utm_campaign=api-credit" title="Unsplash" target="_blank">Unsplash</a></em>
            {% endif %}

            <a target="_blank" class="create" href="https://{{ request.site.domain }}{% url "main:home" %}">Create your own TimeTaco</a>

        </article>
        {% if host %}
        <script>
        window.addEventListener('DOMContentLoaded', function() {

            window.parent.postMessage({
                                    'height': document.getElementById('timetaco-embed').offsetHeight,
                                    'timetaco-id': '{{ countdown.id }}'
                                    }, '{{ host }}');

        }, false);
        </script>
        {% endif %}
    </body>
</html>

main/templates/login_overlay.html
{% if not request.user.is_authenticated %}
<section class="overlay" data-overlay="login">
	<div>
		<h2 class="overlay-header"><span>Login</span>
		<a href="javascript:void(0);" data-closeoverlay class="close-button"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" style="pointer-events: none; display: block; width: 100%; height: 100%;"><g><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"></path></g></svg></a></h2>

	    <p>
	        To sign up or log in, just enter your email address below and click the link we send you:
	    </p>

	    <form class="login" action="{% url "tokenauth:login" %}?next={{ request.GET.next }}" method="post">{% csrf_token %}
	        <input required type="email" placeholder="Enter your email" name="email"/>
	        <button class="button login" type="submit">Login</button>
	    </form>
	</div>
</section>
{% endif %}